FROM nginx:1.9
MAINTAINER James Cowie <james@jcowie.co.uk>

COPY ./default.conf /etc/nginx/conf.d/
COPY ./nginx.conf.sample /etc/nginx/conf.d/
COPY ./nginx.crt /etc/nginx/
COPY ./nginx.key /etc/nginx/
