FROM nginx:1.9
MAINTAINER Gordon Knoppe <gknoppe@magento.com>

COPY ./default.conf /etc/nginx/conf.d/
COPY ./nginx.conf.sample /etc/nginx/conf.d/
COPY ./nginx.crt /etc/nginx/
COPY ./nginx.key /etc/nginx/
